
repo_keyalias: cs-650171438317-default


keydname: CN=cs-650171438317-default, OU=F-Droid


keystorepass: MS5tmJG0escP3PqefLziYTqI8ideMSiywjgWZKhMLKY=


keypass: MS5tmJG0escP3PqefLziYTqI8ideMSiywjgWZKhMLKY=

